//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DVOscarParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class DVOscarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ASSOCIATED=1, BEGIN=2, COLON=3, COMMA=4, COUNT=5, DATASTORE=6, DATATYPE=7, 
		BOOLEAN=8, DATE=9, DEFAULT=10, END=11, END_DATASTORE=12, END_ITEM=13, 
		EQUAL=14, FALSE=15, CHARACTER=16, FLOAT=17, GUID=18, ITEM=19, KEY=20, 
		LBRACK=21, LCURLY=22, LENGTH=23, LPAREN=24, NULL=25, PLURAL=26, RBRACK=27, 
		RCURLY=28, RPAREN=29, SCALE=30, UNDERSCORE=31, INTEGER=32, MANY_TO_MANY=33, 
		MINUS=34, NUMBER_INT=35, NUMBER_FLOAT=36, NUMBER=37, NUMERIC=38, ONE_TO_ONE=39, 
		PLUS=40, PRECISION=41, STRING=42, STRING_LITERAL=43, TIME=44, DATETIME=45, 
		TRUE=46, IDENTIFIER=47, SPACE=48, COMMENT=49, LINE_COMMENT=50;
	public const int
		RULE_dvoscar_file = 0, RULE_block = 1, RULE_datastore_statements = 2, 
		RULE_datastore_statement = 3, RULE_parent_item_statement = 4, RULE_item_statement = 5, 
		RULE_child_item_statement = 6, RULE_associations = 7, RULE_association_def = 8, 
		RULE_cardinality = 9, RULE_o2o = 10, RULE_m2m = 11, RULE_from_key = 12, 
		RULE_to_key = 13, RULE_attribute_def = 14, RULE_precision_def = 15, RULE_scale_def = 16, 
		RULE_length_def = 17, RULE_default_value = 18, RULE_identifier = 19, RULE_properties = 20, 
		RULE_property = 21, RULE_pair = 22, RULE_display_name = 23, RULE_plural = 24, 
		RULE_array = 25, RULE_function_call = 26, RULE_arguments = 27, RULE_argument = 28, 
		RULE_value = 29, RULE_integer_value = 30, RULE_constant = 31, RULE_sign = 32;
	public static readonly string[] ruleNames = {
		"dvoscar_file", "block", "datastore_statements", "datastore_statement", 
		"parent_item_statement", "item_statement", "child_item_statement", "associations", 
		"association_def", "cardinality", "o2o", "m2m", "from_key", "to_key", 
		"attribute_def", "precision_def", "scale_def", "length_def", "default_value", 
		"identifier", "properties", "property", "pair", "display_name", "plural", 
		"array", "function_call", "arguments", "argument", "value", "integer_value", 
		"constant", "sign"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "':'", "','", null, null, null, null, null, null, null, 
		null, null, "'='", null, null, null, null, null, null, "'['", "'{'", null, 
		"'('", null, null, "']'", "'}'", "')'", null, "'_'", null, null, "'-'", 
		null, null, null, null, null, "'+'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ASSOCIATED", "BEGIN", "COLON", "COMMA", "COUNT", "DATASTORE", "DATATYPE", 
		"BOOLEAN", "DATE", "DEFAULT", "END", "END_DATASTORE", "END_ITEM", "EQUAL", 
		"FALSE", "CHARACTER", "FLOAT", "GUID", "ITEM", "KEY", "LBRACK", "LCURLY", 
		"LENGTH", "LPAREN", "NULL", "PLURAL", "RBRACK", "RCURLY", "RPAREN", "SCALE", 
		"UNDERSCORE", "INTEGER", "MANY_TO_MANY", "MINUS", "NUMBER_INT", "NUMBER_FLOAT", 
		"NUMBER", "NUMERIC", "ONE_TO_ONE", "PLUS", "PRECISION", "STRING", "STRING_LITERAL", 
		"TIME", "DATETIME", "TRUE", "IDENTIFIER", "SPACE", "COMMENT", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DVOscarParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DVOscarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DVOscarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DVOscarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Dvoscar_fileContext : ParserRuleContext {
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(DVOscarParser.Eof, 0); }
		public Dvoscar_fileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dvoscar_file; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterDvoscar_file(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitDvoscar_file(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDvoscar_file(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Dvoscar_fileContext dvoscar_file() {
		Dvoscar_fileContext _localctx = new Dvoscar_fileContext(Context, State);
		EnterRule(_localctx, 0, RULE_dvoscar_file);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66; block();
			State = 67; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode BEGIN() { return GetToken(DVOscarParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(DVOscarParser.END, 0); }
		public Datastore_statementsContext[] datastore_statements() {
			return GetRuleContexts<Datastore_statementsContext>();
		}
		public Datastore_statementsContext datastore_statements(int i) {
			return GetRuleContext<Datastore_statementsContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; Match(BEGIN);
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 70; datastore_statements();
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==DATASTORE );
			State = 75; Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Datastore_statementsContext : ParserRuleContext {
		public Datastore_statementContext[] datastore_statement() {
			return GetRuleContexts<Datastore_statementContext>();
		}
		public Datastore_statementContext datastore_statement(int i) {
			return GetRuleContext<Datastore_statementContext>(i);
		}
		public Datastore_statementsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_datastore_statements; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterDatastore_statements(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitDatastore_statements(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDatastore_statements(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Datastore_statementsContext datastore_statements() {
		Datastore_statementsContext _localctx = new Datastore_statementsContext(Context, State);
		EnterRule(_localctx, 4, RULE_datastore_statements);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 77; datastore_statement();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 80;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Datastore_statementContext : ParserRuleContext {
		public ITerminalNode DATASTORE() { return GetToken(DVOscarParser.DATASTORE, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode END_DATASTORE() { return GetToken(DVOscarParser.END_DATASTORE, 0); }
		public Display_nameContext display_name() {
			return GetRuleContext<Display_nameContext>(0);
		}
		public PropertiesContext properties() {
			return GetRuleContext<PropertiesContext>(0);
		}
		public Parent_item_statementContext[] parent_item_statement() {
			return GetRuleContexts<Parent_item_statementContext>();
		}
		public Parent_item_statementContext parent_item_statement(int i) {
			return GetRuleContext<Parent_item_statementContext>(i);
		}
		public Datastore_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_datastore_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterDatastore_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitDatastore_statement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDatastore_statement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Datastore_statementContext datastore_statement() {
		Datastore_statementContext _localctx = new Datastore_statementContext(Context, State);
		EnterRule(_localctx, 6, RULE_datastore_statement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82; Match(DATASTORE);
			State = 83; identifier();
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING_LITERAL) {
				{
				State = 84; display_name();
				}
			}

			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LCURLY) {
				{
				State = 87; properties();
				}
			}

			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 90; parent_item_statement();
				}
				}
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==ITEM );
			State = 95; Match(END_DATASTORE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Parent_item_statementContext : ParserRuleContext {
		public Item_statementContext[] item_statement() {
			return GetRuleContexts<Item_statementContext>();
		}
		public Item_statementContext item_statement(int i) {
			return GetRuleContext<Item_statementContext>(i);
		}
		public Parent_item_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parent_item_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterParent_item_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitParent_item_statement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParent_item_statement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Parent_item_statementContext parent_item_statement() {
		Parent_item_statementContext _localctx = new Parent_item_statementContext(Context, State);
		EnterRule(_localctx, 8, RULE_parent_item_statement);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 98;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 97; item_statement();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 100;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Item_statementContext : ParserRuleContext {
		public ITerminalNode ITEM() { return GetToken(DVOscarParser.ITEM, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode END_ITEM() { return GetToken(DVOscarParser.END_ITEM, 0); }
		public PluralContext plural() {
			return GetRuleContext<PluralContext>(0);
		}
		public Display_nameContext display_name() {
			return GetRuleContext<Display_nameContext>(0);
		}
		public PropertiesContext properties() {
			return GetRuleContext<PropertiesContext>(0);
		}
		public AssociationsContext associations() {
			return GetRuleContext<AssociationsContext>(0);
		}
		public Attribute_defContext[] attribute_def() {
			return GetRuleContexts<Attribute_defContext>();
		}
		public Attribute_defContext attribute_def(int i) {
			return GetRuleContext<Attribute_defContext>(i);
		}
		public Child_item_statementContext child_item_statement() {
			return GetRuleContext<Child_item_statementContext>(0);
		}
		public Item_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_item_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterItem_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitItem_statement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitItem_statement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Item_statementContext item_statement() {
		Item_statementContext _localctx = new Item_statementContext(Context, State);
		EnterRule(_localctx, 10, RULE_item_statement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(ITEM);
			State = 103; identifier();
			State = 105;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PLURAL) {
				{
				State = 104; plural();
				}
			}

			State = 108;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING_LITERAL) {
				{
				State = 107; display_name();
				}
			}

			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LCURLY) {
				{
				State = 110; properties();
				}
			}

			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSOCIATED) {
				{
				State = 113; associations();
				}
			}

			State = 117;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 116; attribute_def();
				}
				}
				State = 119;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==IDENTIFIER );
			State = 122;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ITEM) {
				{
				State = 121; child_item_statement();
				}
			}

			State = 124; Match(END_ITEM);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Child_item_statementContext : ParserRuleContext {
		public Item_statementContext[] item_statement() {
			return GetRuleContexts<Item_statementContext>();
		}
		public Item_statementContext item_statement(int i) {
			return GetRuleContext<Item_statementContext>(i);
		}
		public Child_item_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_child_item_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterChild_item_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitChild_item_statement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitChild_item_statement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Child_item_statementContext child_item_statement() {
		Child_item_statementContext _localctx = new Child_item_statementContext(Context, State);
		EnterRule(_localctx, 12, RULE_child_item_statement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 126; item_statement();
				}
				}
				State = 129;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==ITEM );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssociationsContext : ParserRuleContext {
		public Association_defContext[] association_def() {
			return GetRuleContexts<Association_defContext>();
		}
		public Association_defContext association_def(int i) {
			return GetRuleContext<Association_defContext>(i);
		}
		public AssociationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_associations; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterAssociations(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitAssociations(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssociations(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssociationsContext associations() {
		AssociationsContext _localctx = new AssociationsContext(Context, State);
		EnterRule(_localctx, 14, RULE_associations);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 131; association_def();
				}
				}
				State = 134;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==ASSOCIATED );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Association_defContext : ParserRuleContext {
		public ITerminalNode ASSOCIATED() { return GetToken(DVOscarParser.ASSOCIATED, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public CardinalityContext cardinality() {
			return GetRuleContext<CardinalityContext>(0);
		}
		public PropertiesContext properties() {
			return GetRuleContext<PropertiesContext>(0);
		}
		public Association_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_association_def; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterAssociation_def(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitAssociation_def(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssociation_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Association_defContext association_def() {
		Association_defContext _localctx = new Association_defContext(Context, State);
		EnterRule(_localctx, 16, RULE_association_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136; Match(ASSOCIATED);
			State = 137; identifier();
			State = 138; cardinality();
			State = 140;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LCURLY) {
				{
				State = 139; properties();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CardinalityContext : ParserRuleContext {
		public O2oContext o2o() {
			return GetRuleContext<O2oContext>(0);
		}
		public M2mContext m2m() {
			return GetRuleContext<M2mContext>(0);
		}
		public CardinalityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cardinality; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterCardinality(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitCardinality(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCardinality(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CardinalityContext cardinality() {
		CardinalityContext _localctx = new CardinalityContext(Context, State);
		EnterRule(_localctx, 18, RULE_cardinality);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ONE_TO_ONE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 142; o2o();
				}
				break;
			case MANY_TO_MANY:
				EnterOuterAlt(_localctx, 2);
				{
				State = 143; m2m();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class O2oContext : ParserRuleContext {
		public ITerminalNode ONE_TO_ONE() { return GetToken(DVOscarParser.ONE_TO_ONE, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public From_keyContext from_key() {
			return GetRuleContext<From_keyContext>(0);
		}
		public To_keyContext to_key() {
			return GetRuleContext<To_keyContext>(0);
		}
		public O2oContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_o2o; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterO2o(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitO2o(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitO2o(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public O2oContext o2o() {
		O2oContext _localctx = new O2oContext(Context, State);
		EnterRule(_localctx, 20, RULE_o2o);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146; Match(ONE_TO_ONE);
			State = 147; identifier();
			State = 148; from_key();
			State = 149; to_key();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class M2mContext : ParserRuleContext {
		public ITerminalNode MANY_TO_MANY() { return GetToken(DVOscarParser.MANY_TO_MANY, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public From_keyContext from_key() {
			return GetRuleContext<From_keyContext>(0);
		}
		public To_keyContext to_key() {
			return GetRuleContext<To_keyContext>(0);
		}
		public M2mContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_m2m; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterM2m(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitM2m(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitM2m(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public M2mContext m2m() {
		M2mContext _localctx = new M2mContext(Context, State);
		EnterRule(_localctx, 22, RULE_m2m);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151; Match(MANY_TO_MANY);
			State = 152; identifier();
			State = 153; from_key();
			State = 154; to_key();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class From_keyContext : ParserRuleContext {
		public ITerminalNode KEY() { return GetToken(DVOscarParser.KEY, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public From_keyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_from_key; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterFrom_key(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitFrom_key(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFrom_key(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public From_keyContext from_key() {
		From_keyContext _localctx = new From_keyContext(Context, State);
		EnterRule(_localctx, 24, RULE_from_key);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156; Match(KEY);
			State = 157; identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class To_keyContext : ParserRuleContext {
		public ITerminalNode KEY() { return GetToken(DVOscarParser.KEY, 0); }
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public To_keyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_to_key; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterTo_key(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitTo_key(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTo_key(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public To_keyContext to_key() {
		To_keyContext _localctx = new To_keyContext(Context, State);
		EnterRule(_localctx, 26, RULE_to_key);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159; Match(KEY);
			State = 160; identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Attribute_defContext : ParserRuleContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode DATATYPE() { return GetToken(DVOscarParser.DATATYPE, 0); }
		public Length_defContext length_def() {
			return GetRuleContext<Length_defContext>(0);
		}
		public Precision_defContext precision_def() {
			return GetRuleContext<Precision_defContext>(0);
		}
		public Scale_defContext scale_def() {
			return GetRuleContext<Scale_defContext>(0);
		}
		public Default_valueContext default_value() {
			return GetRuleContext<Default_valueContext>(0);
		}
		public PropertiesContext properties() {
			return GetRuleContext<PropertiesContext>(0);
		}
		public Display_nameContext display_name() {
			return GetRuleContext<Display_nameContext>(0);
		}
		public Attribute_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute_def; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterAttribute_def(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitAttribute_def(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttribute_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Attribute_defContext attribute_def() {
		Attribute_defContext _localctx = new Attribute_defContext(Context, State);
		EnterRule(_localctx, 28, RULE_attribute_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 162; identifier();
			State = 163; Match(DATATYPE);
			State = 165;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LENGTH) {
				{
				State = 164; length_def();
				}
			}

			State = 168;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PRECISION) {
				{
				State = 167; precision_def();
				}
			}

			State = 171;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SCALE) {
				{
				State = 170; scale_def();
				}
			}

			State = 174;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DEFAULT) {
				{
				State = 173; default_value();
				}
			}

			State = 177;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LCURLY) {
				{
				State = 176; properties();
				}
			}

			State = 180;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==STRING_LITERAL) {
				{
				State = 179; display_name();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Precision_defContext : ParserRuleContext {
		public ITerminalNode PRECISION() { return GetToken(DVOscarParser.PRECISION, 0); }
		public ITerminalNode NUMBER_INT() { return GetToken(DVOscarParser.NUMBER_INT, 0); }
		public Precision_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_precision_def; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterPrecision_def(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitPrecision_def(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrecision_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Precision_defContext precision_def() {
		Precision_defContext _localctx = new Precision_defContext(Context, State);
		EnterRule(_localctx, 30, RULE_precision_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182; Match(PRECISION);
			State = 183; Match(NUMBER_INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Scale_defContext : ParserRuleContext {
		public ITerminalNode SCALE() { return GetToken(DVOscarParser.SCALE, 0); }
		public ITerminalNode NUMBER_INT() { return GetToken(DVOscarParser.NUMBER_INT, 0); }
		public Scale_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scale_def; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterScale_def(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitScale_def(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScale_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Scale_defContext scale_def() {
		Scale_defContext _localctx = new Scale_defContext(Context, State);
		EnterRule(_localctx, 32, RULE_scale_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185; Match(SCALE);
			State = 186; Match(NUMBER_INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Length_defContext : ParserRuleContext {
		public ITerminalNode LENGTH() { return GetToken(DVOscarParser.LENGTH, 0); }
		public Integer_valueContext integer_value() {
			return GetRuleContext<Integer_valueContext>(0);
		}
		public Length_defContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_length_def; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterLength_def(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitLength_def(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLength_def(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Length_defContext length_def() {
		Length_defContext _localctx = new Length_defContext(Context, State);
		EnterRule(_localctx, 34, RULE_length_def);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188; Match(LENGTH);
			State = 189; integer_value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Default_valueContext : ParserRuleContext {
		public ITerminalNode DEFAULT() { return GetToken(DVOscarParser.DEFAULT, 0); }
		public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		public Function_callContext function_call() {
			return GetRuleContext<Function_callContext>(0);
		}
		public Default_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_default_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterDefault_value(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitDefault_value(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefault_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Default_valueContext default_value() {
		Default_valueContext _localctx = new Default_valueContext(Context, State);
		EnterRule(_localctx, 36, RULE_default_value);
		try {
			State = 195;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 191; Match(DEFAULT);
				State = 192; constant();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 193; Match(DEFAULT);
				State = 194; function_call();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(DVOscarParser.IDENTIFIER, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 38, RULE_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertiesContext : ParserRuleContext {
		public PropertyContext[] property() {
			return GetRuleContexts<PropertyContext>();
		}
		public PropertyContext property(int i) {
			return GetRuleContext<PropertyContext>(i);
		}
		public PropertiesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_properties; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterProperties(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitProperties(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProperties(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertiesContext properties() {
		PropertiesContext _localctx = new PropertiesContext(Context, State);
		EnterRule(_localctx, 40, RULE_properties);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 199; property();
				}
				}
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==LCURLY );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyContext : ParserRuleContext {
		public ITerminalNode LCURLY() { return GetToken(DVOscarParser.LCURLY, 0); }
		public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ITerminalNode RCURLY() { return GetToken(DVOscarParser.RCURLY, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(DVOscarParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(DVOscarParser.COMMA, i);
		}
		public PropertyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_property; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterProperty(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitProperty(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProperty(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyContext property() {
		PropertyContext _localctx = new PropertyContext(Context, State);
		EnterRule(_localctx, 42, RULE_property);
		int _la;
		try {
			State = 217;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 204; Match(LCURLY);
				State = 205; pair();
				State = 210;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 206; Match(COMMA);
					State = 207; pair();
					}
					}
					State = 212;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 213; Match(RCURLY);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 215; Match(LCURLY);
				State = 216; Match(RCURLY);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		public ITerminalNode STRING_LITERAL() { return GetToken(DVOscarParser.STRING_LITERAL, 0); }
		public ITerminalNode COLON() { return GetToken(DVOscarParser.COLON, 0); }
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterPair(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitPair(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPair(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 44, RULE_pair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 219; Match(STRING_LITERAL);
			State = 220; Match(COLON);
			State = 221; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Display_nameContext : ParserRuleContext {
		public ITerminalNode STRING_LITERAL() { return GetToken(DVOscarParser.STRING_LITERAL, 0); }
		public Display_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_display_name; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterDisplay_name(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitDisplay_name(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDisplay_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Display_nameContext display_name() {
		Display_nameContext _localctx = new Display_nameContext(Context, State);
		EnterRule(_localctx, 46, RULE_display_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 223; Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PluralContext : ParserRuleContext {
		public ITerminalNode PLURAL() { return GetToken(DVOscarParser.PLURAL, 0); }
		public ITerminalNode STRING_LITERAL() { return GetToken(DVOscarParser.STRING_LITERAL, 0); }
		public PluralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_plural; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterPlural(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitPlural(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlural(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PluralContext plural() {
		PluralContext _localctx = new PluralContext(Context, State);
		EnterRule(_localctx, 48, RULE_plural);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225; Match(PLURAL);
			State = 226; Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		public ITerminalNode LBRACK() { return GetToken(DVOscarParser.LBRACK, 0); }
		public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ITerminalNode RBRACK() { return GetToken(DVOscarParser.RBRACK, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(DVOscarParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(DVOscarParser.COMMA, i);
		}
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterArray(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitArray(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 50, RULE_array);
		int _la;
		try {
			State = 241;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 228; Match(LBRACK);
				State = 229; value();
				State = 234;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 230; Match(COMMA);
					State = 231; value();
					}
					}
					State = 236;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 237; Match(RBRACK);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 239; Match(LBRACK);
				State = 240; Match(RBRACK);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_callContext : ParserRuleContext {
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ITerminalNode LPAREN() { return GetToken(DVOscarParser.LPAREN, 0); }
		public ITerminalNode RPAREN() { return GetToken(DVOscarParser.RPAREN, 0); }
		public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public Function_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_call; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterFunction_call(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitFunction_call(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction_call(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Function_callContext function_call() {
		Function_callContext _localctx = new Function_callContext(Context, State);
		EnterRule(_localctx, 52, RULE_function_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 243; identifier();
			State = 244; Match(LPAREN);
			State = 246;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << FALSE) | (1L << LBRACK) | (1L << NULL) | (1L << MINUS) | (1L << NUMBER_INT) | (1L << NUMBER_FLOAT) | (1L << PLUS) | (1L << STRING_LITERAL) | (1L << TRUE) | (1L << IDENTIFIER))) != 0)) {
				{
				State = 245; arguments();
				}
			}

			State = 248; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentsContext : ParserRuleContext {
		public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(DVOscarParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(DVOscarParser.COMMA, i);
		}
		public ArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterArguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitArguments(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentsContext arguments() {
		ArgumentsContext _localctx = new ArgumentsContext(Context, State);
		EnterRule(_localctx, 54, RULE_arguments);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250; argument();
			State = 255;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 251; Match(COMMA);
				State = 252; argument();
				}
				}
				State = 257;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		public Function_callContext function_call() {
			return GetRuleContext<Function_callContext>(0);
		}
		public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterArgument(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitArgument(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 56, RULE_argument);
		try {
			State = 261;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 258; function_call();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 259; identifier();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 260; value();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		public ITerminalNode TRUE() { return GetToken(DVOscarParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(DVOscarParser.FALSE, 0); }
		public ITerminalNode NULL() { return GetToken(DVOscarParser.NULL, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 58, RULE_value);
		try {
			State = 268;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MINUS:
			case NUMBER_INT:
			case NUMBER_FLOAT:
			case PLUS:
			case STRING_LITERAL:
				EnterOuterAlt(_localctx, 1);
				{
				State = 263; constant();
				}
				break;
			case LBRACK:
				EnterOuterAlt(_localctx, 2);
				{
				State = 264; array();
				}
				break;
			case TRUE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 265; Match(TRUE);
				}
				break;
			case FALSE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 266; Match(FALSE);
				}
				break;
			case NULL:
				EnterOuterAlt(_localctx, 5);
				{
				State = 267; Match(NULL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Integer_valueContext : ParserRuleContext {
		public ITerminalNode NUMBER_INT() { return GetToken(DVOscarParser.NUMBER_INT, 0); }
		public SignContext sign() {
			return GetRuleContext<SignContext>(0);
		}
		public Integer_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_integer_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterInteger_value(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitInteger_value(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteger_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Integer_valueContext integer_value() {
		Integer_valueContext _localctx = new Integer_valueContext(Context, State);
		EnterRule(_localctx, 60, RULE_integer_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 271;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MINUS || _la==PLUS) {
				{
				State = 270; sign();
				}
			}

			State = 273; Match(NUMBER_INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantContext : ParserRuleContext {
		public ITerminalNode STRING_LITERAL() { return GetToken(DVOscarParser.STRING_LITERAL, 0); }
		public Integer_valueContext integer_value() {
			return GetRuleContext<Integer_valueContext>(0);
		}
		public ITerminalNode NUMBER_FLOAT() { return GetToken(DVOscarParser.NUMBER_FLOAT, 0); }
		public SignContext sign() {
			return GetRuleContext<SignContext>(0);
		}
		public ConstantContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterConstant(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitConstant(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstant(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstantContext constant() {
		ConstantContext _localctx = new ConstantContext(Context, State);
		EnterRule(_localctx, 62, RULE_constant);
		int _la;
		try {
			State = 281;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,34,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 275; Match(STRING_LITERAL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 276; integer_value();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 278;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==MINUS || _la==PLUS) {
					{
					State = 277; sign();
					}
				}

				State = 280; Match(NUMBER_FLOAT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SignContext : ParserRuleContext {
		public ITerminalNode PLUS() { return GetToken(DVOscarParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(DVOscarParser.MINUS, 0); }
		public SignContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sign; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.EnterSign(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDVOscarParserListener typedListener = listener as IDVOscarParserListener;
			if (typedListener != null) typedListener.ExitSign(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDVOscarParserVisitor<TResult> typedVisitor = visitor as IDVOscarParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSign(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SignContext sign() {
		SignContext _localctx = new SignContext(Context, State);
		EnterRule(_localctx, 64, RULE_sign);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			_la = TokenStream.LA(1);
			if ( !(_la==MINUS || _la==PLUS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x34', '\x120', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x6', 
		'\x3', 'J', '\n', '\x3', '\r', '\x3', '\xE', '\x3', 'K', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x6', '\x4', 'Q', '\n', '\x4', '\r', '\x4', 
		'\xE', '\x4', 'R', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 
		'X', '\n', '\x5', '\x3', '\x5', '\x5', '\x5', '[', '\n', '\x5', '\x3', 
		'\x5', '\x6', '\x5', '^', '\n', '\x5', '\r', '\x5', '\xE', '\x5', '_', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x6', '\x6', '\x65', '\n', 
		'\x6', '\r', '\x6', '\xE', '\x6', '\x66', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x5', '\a', 'l', '\n', '\a', '\x3', '\a', '\x5', '\a', 'o', '\n', 
		'\a', '\x3', '\a', '\x5', '\a', 'r', '\n', '\a', '\x3', '\a', '\x5', '\a', 
		'u', '\n', '\a', '\x3', '\a', '\x6', '\a', 'x', '\n', '\a', '\r', '\a', 
		'\xE', '\a', 'y', '\x3', '\a', '\x5', '\a', '}', '\n', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x6', '\b', '\x82', '\n', '\b', '\r', '\b', 
		'\xE', '\b', '\x83', '\x3', '\t', '\x6', '\t', '\x87', '\n', '\t', '\r', 
		'\t', '\xE', '\t', '\x88', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x5', '\n', '\x8F', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x5', 
		'\v', '\x93', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\xA8', '\n', '\x10', '\x3', '\x10', '\x5', '\x10', '\xAB', '\n', 
		'\x10', '\x3', '\x10', '\x5', '\x10', '\xAE', '\n', '\x10', '\x3', '\x10', 
		'\x5', '\x10', '\xB1', '\n', '\x10', '\x3', '\x10', '\x5', '\x10', '\xB4', 
		'\n', '\x10', '\x3', '\x10', '\x5', '\x10', '\xB7', '\n', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\xC6', '\n', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x6', '\x16', '\xCB', '\n', 
		'\x16', '\r', '\x16', '\xE', '\x16', '\xCC', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\xD3', '\n', '\x17', '\f', 
		'\x17', '\xE', '\x17', '\xD6', '\v', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\xDC', '\n', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', '\xEB', '\n', '\x1B', 
		'\f', '\x1B', '\xE', '\x1B', '\xEE', '\v', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', '\xF4', '\n', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x5', '\x1C', '\xF9', '\n', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\a', '\x1D', '\x100', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', 
		'\x103', '\v', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x5', 
		'\x1E', '\x108', '\n', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x5', '\x1F', '\x10F', '\n', '\x1F', '\x3', 
		' ', '\x5', ' ', '\x112', '\n', ' ', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x3', '!', '\x3', '!', '\x5', '!', '\x119', '\n', '!', '\x3', '!', '\x5', 
		'!', '\x11C', '\n', '!', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x2', 
		'\x2', '#', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', ',', '.', '\x30', '\x32', '\x34', '\x36', '\x38', ':', '<', '>', 
		'@', '\x42', '\x2', '\x3', '\x4', '\x2', '$', '$', '*', '*', '\x2', '\x126', 
		'\x2', '\x44', '\x3', '\x2', '\x2', '\x2', '\x4', 'G', '\x3', '\x2', '\x2', 
		'\x2', '\x6', 'P', '\x3', '\x2', '\x2', '\x2', '\b', 'T', '\x3', '\x2', 
		'\x2', '\x2', '\n', '\x64', '\x3', '\x2', '\x2', '\x2', '\f', 'h', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\x81', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x12', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '\x14', '\x92', '\x3', '\x2', '\x2', '\x2', '\x16', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x99', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\xA4', '\x3', '\x2', '\x2', '\x2', ' ', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\"', '\xBB', '\x3', '\x2', '\x2', '\x2', '$', '\xBE', 
		'\x3', '\x2', '\x2', '\x2', '&', '\xC5', '\x3', '\x2', '\x2', '\x2', '(', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '*', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', ',', '\xDB', '\x3', '\x2', '\x2', '\x2', '.', '\xDD', '\x3', '\x2', 
		'\x2', '\x2', '\x30', '\xE1', '\x3', '\x2', '\x2', '\x2', '\x32', '\xE3', 
		'\x3', '\x2', '\x2', '\x2', '\x34', '\xF3', '\x3', '\x2', '\x2', '\x2', 
		'\x36', '\xF5', '\x3', '\x2', '\x2', '\x2', '\x38', '\xFC', '\x3', '\x2', 
		'\x2', '\x2', ':', '\x107', '\x3', '\x2', '\x2', '\x2', '<', '\x10E', 
		'\x3', '\x2', '\x2', '\x2', '>', '\x111', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x11B', '\x3', '\x2', '\x2', '\x2', '\x42', '\x11D', '\x3', '\x2', 
		'\x2', '\x2', '\x44', '\x45', '\x5', '\x4', '\x3', '\x2', '\x45', '\x46', 
		'\a', '\x2', '\x2', '\x3', '\x46', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'G', 'I', '\a', '\x4', '\x2', '\x2', 'H', 'J', '\x5', '\x6', '\x4', '\x2', 
		'I', 'H', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 
		'K', 'I', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', '\r', '\x2', '\x2', 
		'N', '\x5', '\x3', '\x2', '\x2', '\x2', 'O', 'Q', '\x5', '\b', '\x5', 
		'\x2', 'P', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'S', '\a', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', '\b', '\x2', 
		'\x2', 'U', 'W', '\x5', '(', '\x15', '\x2', 'V', 'X', '\x5', '\x30', '\x19', 
		'\x2', 'W', 'V', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 'Y', '[', '\x5', '*', '\x16', 
		'\x2', 'Z', 'Y', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', 
		'\x2', '[', ']', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\x5', '\n', '\x6', 
		'\x2', ']', '\\', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', 
		'\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', 
		'\a', '\xE', '\x2', '\x2', '\x62', '\t', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x65', '\x5', '\f', '\a', '\x2', '\x64', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x66', '\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', 
		'\x2', '\x2', '\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', '\v', 
		'\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '\x15', '\x2', '\x2', 'i', 
		'k', '\x5', '(', '\x15', '\x2', 'j', 'l', '\x5', '\x32', '\x1A', '\x2', 
		'k', 'j', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 
		'l', 'n', '\x3', '\x2', '\x2', '\x2', 'm', 'o', '\x5', '\x30', '\x19', 
		'\x2', 'n', 'm', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 'p', 'r', '\x5', '*', '\x16', 
		'\x2', 'q', 'p', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', 
		'\x2', 'r', 't', '\x3', '\x2', '\x2', '\x2', 's', 'u', '\x5', '\x10', 
		'\t', '\x2', 't', 's', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'w', '\x3', '\x2', '\x2', '\x2', 'v', 'x', '\x5', '\x1E', 
		'\x10', '\x2', 'w', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'w', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\x3', 
		'\x2', '\x2', '\x2', 'z', '|', '\x3', '\x2', '\x2', '\x2', '{', '}', '\x5', 
		'\xE', '\b', '\x2', '|', '{', '\x3', '\x2', '\x2', '\x2', '|', '}', '\x3', 
		'\x2', '\x2', '\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', 
		'\a', '\xF', '\x2', '\x2', '\x7F', '\r', '\x3', '\x2', '\x2', '\x2', '\x80', 
		'\x82', '\x5', '\f', '\a', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x85', '\x87', '\x5', '\x12', '\n', 
		'\x2', '\x86', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x89', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', '\x3', '\x2', '\x2', '\x8B', '\x8C', '\x5', 
		'(', '\x15', '\x2', '\x8C', '\x8E', '\x5', '\x14', '\v', '\x2', '\x8D', 
		'\x8F', '\x5', '*', '\x16', '\x2', '\x8E', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x93', '\x5', '\x16', '\f', '\x2', '\x91', 
		'\x93', '\x5', '\x18', '\r', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x95', '\a', ')', '\x2', '\x2', '\x95', 
		'\x96', '\x5', '(', '\x15', '\x2', '\x96', '\x97', '\x5', '\x1A', '\xE', 
		'\x2', '\x97', '\x98', '\x5', '\x1C', '\xF', '\x2', '\x98', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '#', '\x2', '\x2', '\x9A', 
		'\x9B', '\x5', '(', '\x15', '\x2', '\x9B', '\x9C', '\x5', '\x1A', '\xE', 
		'\x2', '\x9C', '\x9D', '\x5', '\x1C', '\xF', '\x2', '\x9D', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', '\x16', '\x2', '\x2', '\x9F', 
		'\xA0', '\x5', '(', '\x15', '\x2', '\xA0', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\a', '\x16', '\x2', '\x2', '\xA2', '\xA3', '\x5', 
		'(', '\x15', '\x2', '\xA3', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA5', '\x5', '(', '\x15', '\x2', '\xA5', '\xA7', '\a', '\t', '\x2', 
		'\x2', '\xA6', '\xA8', '\x5', '$', '\x13', '\x2', '\xA7', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAB', '\x5', ' ', '\x11', 
		'\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAE', '\x5', '\"', '\x12', '\x2', '\xAD', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB0', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xB1', '\x5', '&', '\x14', '\x2', '\xB0', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB4', '\x5', 
		'*', '\x16', '\x2', '\xB3', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\xB7', '\x5', '\x30', '\x19', '\x2', '\xB6', '\xB5', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\a', '+', '\x2', 
		'\x2', '\xB9', '\xBA', '\a', '%', '\x2', '\x2', '\xBA', '!', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBC', '\a', ' ', '\x2', '\x2', '\xBC', '\xBD', 
		'\a', '%', '\x2', '\x2', '\xBD', '#', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xBF', '\a', '\x19', '\x2', '\x2', '\xBF', '\xC0', '\x5', '>', ' ', '\x2', 
		'\xC0', '%', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', '\f', '\x2', 
		'\x2', '\xC2', '\xC6', '\x5', '@', '!', '\x2', '\xC3', '\xC4', '\a', '\f', 
		'\x2', '\x2', '\xC4', '\xC6', '\x5', '\x36', '\x1C', '\x2', '\xC5', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', 
		'\xC6', '\'', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\a', '\x31', 
		'\x2', '\x2', '\xC8', ')', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCB', 
		'\x5', ',', '\x17', '\x2', '\xCA', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', '\xCC', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCD', '+', 
		'\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', '\a', '\x18', '\x2', '\x2', 
		'\xCF', '\xD4', '\x5', '.', '\x18', '\x2', '\xD0', '\xD1', '\a', '\x6', 
		'\x2', '\x2', '\xD1', '\xD3', '\x5', '.', '\x18', '\x2', '\xD2', '\xD0', 
		'\x3', '\x2', '\x2', '\x2', '\xD3', '\xD6', '\x3', '\x2', '\x2', '\x2', 
		'\xD4', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\x3', '\x2', 
		'\x2', '\x2', '\xD5', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\a', '\x1E', '\x2', '\x2', 
		'\xD8', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\a', '\x18', 
		'\x2', '\x2', '\xDA', '\xDC', '\a', '\x1E', '\x2', '\x2', '\xDB', '\xCE', 
		'\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', '\x2', '\x2', '\x2', 
		'\xDC', '-', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\a', '-', '\x2', 
		'\x2', '\xDE', '\xDF', '\a', '\x5', '\x2', '\x2', '\xDF', '\xE0', '\x5', 
		'<', '\x1F', '\x2', '\xE0', '/', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', 
		'\a', '-', '\x2', '\x2', '\xE2', '\x31', '\x3', '\x2', '\x2', '\x2', '\xE3', 
		'\xE4', '\a', '\x1C', '\x2', '\x2', '\xE4', '\xE5', '\a', '-', '\x2', 
		'\x2', '\xE5', '\x33', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', '\a', 
		'\x17', '\x2', '\x2', '\xE7', '\xEC', '\x5', '<', '\x1F', '\x2', '\xE8', 
		'\xE9', '\a', '\x6', '\x2', '\x2', '\xE9', '\xEB', '\x5', '<', '\x1F', 
		'\x2', '\xEA', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEE', '\x3', 
		'\x2', '\x2', '\x2', '\xEC', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xED', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEF', '\x3', '\x2', '\x2', 
		'\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF0', '\a', 
		'\x1D', '\x2', '\x2', '\xF0', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF1', 
		'\xF2', '\a', '\x17', '\x2', '\x2', '\xF2', '\xF4', '\a', '\x1D', '\x2', 
		'\x2', '\xF3', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF1', '\x3', 
		'\x2', '\x2', '\x2', '\xF4', '\x35', '\x3', '\x2', '\x2', '\x2', '\xF5', 
		'\xF6', '\x5', '(', '\x15', '\x2', '\xF6', '\xF8', '\a', '\x1A', '\x2', 
		'\x2', '\xF7', '\xF9', '\x5', '\x38', '\x1D', '\x2', '\xF8', '\xF7', '\x3', 
		'\x2', '\x2', '\x2', '\xF8', '\xF9', '\x3', '\x2', '\x2', '\x2', '\xF9', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xFB', '\a', '\x1F', '\x2', 
		'\x2', '\xFB', '\x37', '\x3', '\x2', '\x2', '\x2', '\xFC', '\x101', '\x5', 
		':', '\x1E', '\x2', '\xFD', '\xFE', '\a', '\x6', '\x2', '\x2', '\xFE', 
		'\x100', '\x5', ':', '\x1E', '\x2', '\xFF', '\xFD', '\x3', '\x2', '\x2', 
		'\x2', '\x100', '\x103', '\x3', '\x2', '\x2', '\x2', '\x101', '\xFF', 
		'\x3', '\x2', '\x2', '\x2', '\x101', '\x102', '\x3', '\x2', '\x2', '\x2', 
		'\x102', '\x39', '\x3', '\x2', '\x2', '\x2', '\x103', '\x101', '\x3', 
		'\x2', '\x2', '\x2', '\x104', '\x108', '\x5', '\x36', '\x1C', '\x2', '\x105', 
		'\x108', '\x5', '(', '\x15', '\x2', '\x106', '\x108', '\x5', '<', '\x1F', 
		'\x2', '\x107', '\x104', '\x3', '\x2', '\x2', '\x2', '\x107', '\x105', 
		'\x3', '\x2', '\x2', '\x2', '\x107', '\x106', '\x3', '\x2', '\x2', '\x2', 
		'\x108', ';', '\x3', '\x2', '\x2', '\x2', '\x109', '\x10F', '\x5', '@', 
		'!', '\x2', '\x10A', '\x10F', '\x5', '\x34', '\x1B', '\x2', '\x10B', '\x10F', 
		'\a', '\x30', '\x2', '\x2', '\x10C', '\x10F', '\a', '\x11', '\x2', '\x2', 
		'\x10D', '\x10F', '\a', '\x1B', '\x2', '\x2', '\x10E', '\x109', '\x3', 
		'\x2', '\x2', '\x2', '\x10E', '\x10A', '\x3', '\x2', '\x2', '\x2', '\x10E', 
		'\x10B', '\x3', '\x2', '\x2', '\x2', '\x10E', '\x10C', '\x3', '\x2', '\x2', 
		'\x2', '\x10E', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x10F', '=', '\x3', 
		'\x2', '\x2', '\x2', '\x110', '\x112', '\x5', '\x42', '\"', '\x2', '\x111', 
		'\x110', '\x3', '\x2', '\x2', '\x2', '\x111', '\x112', '\x3', '\x2', '\x2', 
		'\x2', '\x112', '\x113', '\x3', '\x2', '\x2', '\x2', '\x113', '\x114', 
		'\a', '%', '\x2', '\x2', '\x114', '?', '\x3', '\x2', '\x2', '\x2', '\x115', 
		'\x11C', '\a', '-', '\x2', '\x2', '\x116', '\x11C', '\x5', '>', ' ', '\x2', 
		'\x117', '\x119', '\x5', '\x42', '\"', '\x2', '\x118', '\x117', '\x3', 
		'\x2', '\x2', '\x2', '\x118', '\x119', '\x3', '\x2', '\x2', '\x2', '\x119', 
		'\x11A', '\x3', '\x2', '\x2', '\x2', '\x11A', '\x11C', '\a', '&', '\x2', 
		'\x2', '\x11B', '\x115', '\x3', '\x2', '\x2', '\x2', '\x11B', '\x116', 
		'\x3', '\x2', '\x2', '\x2', '\x11B', '\x118', '\x3', '\x2', '\x2', '\x2', 
		'\x11C', '\x41', '\x3', '\x2', '\x2', '\x2', '\x11D', '\x11E', '\t', '\x2', 
		'\x2', '\x2', '\x11E', '\x43', '\x3', '\x2', '\x2', '\x2', '%', 'K', 'R', 
		'W', 'Z', '_', '\x66', 'k', 'n', 'q', 't', 'y', '|', '\x83', '\x88', '\x8E', 
		'\x92', '\xA7', '\xAA', '\xAD', '\xB0', '\xB3', '\xB6', '\xC5', '\xCC', 
		'\xD4', '\xDB', '\xEC', '\xF3', '\xF8', '\x101', '\x107', '\x10E', '\x111', 
		'\x118', '\x11B',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
