//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from I:\DVProjects\IntuitionData\OscarAntlr\DVOscarParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDVOscarParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class DVOscarParserBaseListener : IDVOscarParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.dvoscar_file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDvoscar_file([NotNull] DVOscarParser.Dvoscar_fileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.dvoscar_file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDvoscar_file([NotNull] DVOscarParser.Dvoscar_fileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] DVOscarParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] DVOscarParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.datastore_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatastore_statement([NotNull] DVOscarParser.Datastore_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.datastore_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatastore_statement([NotNull] DVOscarParser.Datastore_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.parent_item_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParent_item_statement([NotNull] DVOscarParser.Parent_item_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.parent_item_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParent_item_statement([NotNull] DVOscarParser.Parent_item_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.item_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem_statement([NotNull] DVOscarParser.Item_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.item_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem_statement([NotNull] DVOscarParser.Item_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.child_item_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChild_item_statement([NotNull] DVOscarParser.Child_item_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.child_item_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChild_item_statement([NotNull] DVOscarParser.Child_item_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.associations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssociations([NotNull] DVOscarParser.AssociationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.associations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssociations([NotNull] DVOscarParser.AssociationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.association_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssociation_def([NotNull] DVOscarParser.Association_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.association_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssociation_def([NotNull] DVOscarParser.Association_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.cardinality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardinality([NotNull] DVOscarParser.CardinalityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.cardinality"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardinality([NotNull] DVOscarParser.CardinalityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.o2o"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterO2o([NotNull] DVOscarParser.O2oContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.o2o"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitO2o([NotNull] DVOscarParser.O2oContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.m2m"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterM2m([NotNull] DVOscarParser.M2mContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.m2m"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitM2m([NotNull] DVOscarParser.M2mContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.m2o"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterM2o([NotNull] DVOscarParser.M2oContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.m2o"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitM2o([NotNull] DVOscarParser.M2oContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.from_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrom_key([NotNull] DVOscarParser.From_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.from_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrom_key([NotNull] DVOscarParser.From_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.to_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTo_key([NotNull] DVOscarParser.To_keyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.to_key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTo_key([NotNull] DVOscarParser.To_keyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.attribute_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_def([NotNull] DVOscarParser.Attribute_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.attribute_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_def([NotNull] DVOscarParser.Attribute_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.attrib_properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrib_properties([NotNull] DVOscarParser.Attrib_propertiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.attrib_properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrib_properties([NotNull] DVOscarParser.Attrib_propertiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.precision_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrecision_def([NotNull] DVOscarParser.Precision_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.precision_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrecision_def([NotNull] DVOscarParser.Precision_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.scale_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScale_def([NotNull] DVOscarParser.Scale_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.scale_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScale_def([NotNull] DVOscarParser.Scale_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.length_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLength_def([NotNull] DVOscarParser.Length_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.length_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLength_def([NotNull] DVOscarParser.Length_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.default_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefault_value([NotNull] DVOscarParser.Default_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.default_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefault_value([NotNull] DVOscarParser.Default_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] DVOscarParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] DVOscarParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.datatype_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatatype_def([NotNull] DVOscarParser.Datatype_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.datatype_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatatype_def([NotNull] DVOscarParser.Datatype_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperties([NotNull] DVOscarParser.PropertiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperties([NotNull] DVOscarParser.PropertiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] DVOscarParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] DVOscarParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] DVOscarParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] DVOscarParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.display_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplay_name([NotNull] DVOscarParser.Display_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.display_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplay_name([NotNull] DVOscarParser.Display_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.plural"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlural([NotNull] DVOscarParser.PluralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.plural"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlural([NotNull] DVOscarParser.PluralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] DVOscarParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] DVOscarParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call([NotNull] DVOscarParser.Function_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call([NotNull] DVOscarParser.Function_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] DVOscarParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] DVOscarParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] DVOscarParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] DVOscarParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] DVOscarParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] DVOscarParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.integer_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger_value([NotNull] DVOscarParser.Integer_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.integer_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger_value([NotNull] DVOscarParser.Integer_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] DVOscarParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] DVOscarParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DVOscarParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSign([NotNull] DVOscarParser.SignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DVOscarParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSign([NotNull] DVOscarParser.SignContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
